; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
;#pragma option -v+
;#pragma verboselevel 9

#define MyAppName "A&D AD310PC"
#define MyAppVersion "1.00"
#define OutputVersion "100"
#define MyAppPublisher "(ÁÖ) ÇÑ±¹ ¿¡ÀÌ¤ý¿£¤ýµð"
#define MyAppURL "http://www.andk.co.kr/"
#define MyAppExeName "AD310PC.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E2D9DF65-FA56-40F1-8BDD-44AF44CCD6C4}
AppName={#MyAppName} {#MyAppVersion}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
LicenseFile={#file AddBackslash(SourcePath) + "ANDLicense.txt"}
OutputBaseFilename=setup
SetupIconFile=
Compression=lzma
SolidCompression=yes

[Languages]
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\PSH\Desktop\AD310PC\AD310PC\bin\Debug\AD310PC.exe"; DestDir: "{app}"; Permissions: admins-full
Source: "C:\WORK\NET Project\AD310PC\resources\SEA_____.TTF"; DestDir: "{fonts}"; Flags: onlyifdoesntexist uninsneveruninstall; FontInstall: "SegmentA1"; Permissions: admins-readexec
Source: "C:\WORK\NET Project\AD310PC\resources\malgun.ttf"; DestDir: "{fonts}"; Flags: onlyifdoesntexist uninsneveruninstall; FontInstall: "¸¼Àº °íµñ"; Permissions: admins-readexec
Source: "C:\WORK\NET Project\AD310PC\resources\malgunbd.ttf"; DestDir: "{fonts}"; Flags: onlyifdoesntexist uninsneveruninstall; FontInstall: "¸¼Àº °íµñ Bold"; Permissions: admins-readexec
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\AD310PC »èÁ¦"; Filename: "{uninstallexe}"; Languages: korean
Name: "{group}\AD310PC"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Flags: nowait postinstall skipifsilent; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Languages: korean


[Messages]
